### ISSUE TITLE
Maybe we should split CreateUpdateTodoDto to CreateTodoDto and UpdateTodoDto

### ISSUE THREAD

**Issue by gdlcf88** [EasyAbp/AbpHelper.CLI#1]
Now it builds the CRUD class with a `CreateUpdateTodoDto`:
```
public class TodoAppService : CrudAppService<Todo, TodoDto, Guid, PagedAndSortedResultRequestDto,
            CreateUpdateTodoDto, CreateUpdateTodoDto>,
        ITodoAppService
```

When developers want a `CreateTodoDto` and a `UpdateTodoDto`, so they should delete `CreateUpdateTodoDto`, create those two new dtos, change `ITodoAppService` and `TodoAppService` and add them to automapper profile manually.

If we build both `CreateTodoDto` and `UpdateTodoDto` to replace `CreateUpdateTodoDto` by default, when developers want to combine them, they can just let `CreateTodoDto` inherit from `UpdateTodoDto`.

**Comment by wakuflair** [comment]
I think the better way is provide an option, e.g. "--SplitCreateAndUpdateDto"?

**Comment by gdlcf88** [comment]
Sure we add a option to control, and which template is the default?

**Comment by wakuflair** [comment]
I recommand to be same with ABP tutorial ---- `CreateAndUpdateDto`.
