### ISSUE TITLE
fix: build failed in VS

### ISSUE THREAD

**Issue by itryan** [EasyAbp/AbpHelper.CLI#10]
build failed in VS with following error:

`CS8630 Invalid 'nullable' value: 'Enable' for C# 7.3. Please use language version '8.0' or greater.`

unless forcing the AbpHelper.csproj to use C# 8.0

```
<PropertyGroup>
   <LangVersion>8.0</LangVersion>
</PropertyGroup
```

**Comment by gdlcf88** [comment]
Maybe your VS need to be upgraded, refer to: https://stackoverflow.com/questions/58624146/feature-using-declarations-is-not-available-in-c-sharp-7-3-please-use-languag

Or we add `<LangVersion>8.0</LangVersion>` to .csproj file.

**Comment by itryan** [comment]
I should update VS to the latest version to continue.
