### ISSUE TITLE
Controller generator should support IReadOnlyAppService

### ISSUE THREAD

**Issue by gdlcf88** [EasyAbp/AbpHelper.CLI#102]
![image](https://user-images.githubusercontent.com/30018771/89293320-4fc27480-d690-11ea-98a9-4b69b9eb712d.png)

**Comment by wakuflair** [comment]
The parser is supposed to be able to get these methods, have you build the application project?

**Comment by gdlcf88** [comment]
I am not sure. I will try it again and reopen this issue if it can be reproduced, thanks @wakuflair.
