### ISSUE TITLE
Improve custom repository template to support customized EfCoreDbContext

### ISSUE THREAD

**Issue by gdlcf88** [EasyAbp/AbpHelper.CLI#104]
See:
* https://docs.abp.io/en/abp/latest/Entity-Framework-Core#set-base-dbcontext-class-or-interface-for-default-repositories
* https://github.com/abpframework/abp/issues/1429#issuecomment-549879532
* https://github.com/EasyAbp/WeChatManagement/issues/6

**Comment by wakuflair** [comment]
Duplicate of #111
