### ISSUE TITLE
Localization generation might need to be moved out from UI generation workflow.

### ISSUE THREAD

**Issue by gdlcf88** [EasyAbp/AbpHelper.CLI#11]
https://github.com/EasyAbp/AbpHelper.CLI/blob/d8ac17b0797980a34f26f7b30c9f2d9559cd31ac/src/AbpHelper/Workflow/Abp/UiRazorPagesGenerationWorkflow.cs#L34

The reasons:
1. Maybe every UI frameworks depends on the localization.
2. Services use the localization too, it means we should create localization even if user disable the UI generator.

**Comment by wakuflair** [comment]
Make sense.
