### ISSUE TITLE
Error when using Controller command with int key Dto

### ISSUE THREAD

**Issue by itryan** [EasyAbp/AbpHelper.CLI#116]
https://github.com/EasyAbp/AbpHelper.CLI/blob/fe8bb39cf86d5a04615228388eb0f0d50aec1ae4/src/AbpHelper/Generator/AbpFunctions.cs#L49-L57

https://github.com/EasyAbp/AbpHelper.CLI/blob/fe8bb39cf86d5a04615228388eb0f0d50aec1ae4/src/AbpHelper/Steps/Abp/ParseStep/BaseParserStep.cs#L120

when Dto is with int key,  `Type.GetType("int")` returns null. may need additional logic to build `idParameterModel.FullType` name.

**Comment by wakuflair** [comment]
Closed with #117
