### ISSUE TITLE
CRUD generator: generate property configurations

### ISSUE THREAD

**Issue by gdlcf88** [EasyAbp/AbpHelper.CLI#123]
Should generate property configurations when the command `generate crud` runs.

```csharp
builder.Entity<Product>(b =>
{
    b.ToTable(MyAppConsts.DbTablePrefix + "Product", MyAppConsts.DbSchema);

    b.ConfigureByConvention(); 

    /* Configure more properties here */

    b.Property(x => x.Name);   // auto generated
    b.Property(x => x.Description);   // auto generated
    b.Property(x => x.Price).HasColumnType("decimal(18, 2)");   // auto generated, 
});
```

**Comment by wakuflair** [comment]
The first two lines are unnecessary, do they have special use?

The last line "HasColumnType` is not likely to be auto generated.

**Comment by gdlcf88** [comment]
Just like the ABP official modules did, maybe configuring Fluent API is a good practice.

`decimal(18, 2)` is EF Core's default column type for a decimal property, if we did not set HasColumnType manually, we will get a warning when using the ef-tools.

**Comment by wakuflair** [comment]
> `decimal(18, 2)` is EF Core's default column type for a decimal property

So why do we need to manually configure it?

**Comment by gdlcf88** [comment]
`decimal(18, 2)` prevents the warning and make the column type clearer. 

However, I am not really sure if we need to create Fluent API configurations like ABP's modules did. 😄

**Comment by wakuflair** [comment]
Close for now. Reopen later if needed.
