### ISSUE TITLE
Command [Generate Crud] does not create a role and a seed for Permissions 

### ISSUE THREAD

**Issue by mrs01dev** [EasyAbp/AbpHelper.CLI#127]
For [Generate crud] Command 
Please add/Generate   a role  with the name of C# class.
Please Seed the New Role to admin user
Thanks

**Comment by wakuflair** [comment]
I think a new role for each entity is not nesscessary.
Could you explain your scenario?

**Comment by mrs01dev** [comment]
Application with  multiple/different   groups of users (Human resource group - accounting group -marketing group - procurement group).
Each Group has it's own web pages [ for group only ,for other groups -request  for vacation/leave - ]
Each Group  will have   it's own Rules.

**Comment by wakuflair** [comment]
The crud command's target is an entity, and will generate permissions for it.
You can create a role and grant these generated permissions to it.
