### ISSUE TITLE
Warning,CS1717,Assignment made to same variable; did you mean to assign something else?

### ISSUE THREAD

**Issue by mrs01dev** [EasyAbp/AbpHelper.CLI#128]
All c# class constructors generated via EasyAbp  AbpHelper.CLI has an issue :
Severity	Code	Description	Project	File	Line	Suppression State
Warning,CS1717,Assignment made to same variable; did you mean to assign something else?	
 I solve  this issue by two regular expression replacement (using notepad Plus Plus):
First replace:
             (.*) (.*),\r\n 
with
	            \1 _\2,\r\n

Second replace:
(.*) = (.*);\r\n
with
            \1 = _\2;\r\n

**Comment by wakuflair** [comment]
Could you give an example about the issue?

**Comment by mrs01dev** [comment]
Here is a sample class:


namespace IssueTracking.Domain.Issues
{
    public class Issue : AggregateRoot<Guid>
    {
        public Guid repositoryId { get; set; }
        public string title { get; set; }
        public string text { get; set; }
        public Guid? assignedUserId { get; set; }
        public bool isClosed { get; set; } = false;
       
       

        protected Issue()
        {
        }

        public Issue(
            Guid id,
            Guid repositoryId,
            string title,
            string text,
            Guid? assignedUserId,
            bool isClosed

        ) : base(id)
        {
            repositoryId = repositoryId;
            title = title;
            text = text;
            assignedUserId = assignedUserId;
            isClosed = isClosed;

        }
    }
}

 camelCase Style is used instead of  PascalCase For public fields, public properties , that is the reason.
Thanks.

**Comment by wakuflair** [comment]
As you said, public properties should be PascalCase, then the warning would be gone.
