### ISSUE TITLE
Missing interface exclusion when entity inherited interfaces

### ISSUE THREAD

**Issue by RayMMond** [EasyAbp/AbpHelper.CLI#130]
According to https://github.com/EasyAbp/AbpHelper.CLI/blob/fe8bb39cf86d5a04615228388eb0f0d50aec1ae4/src/AbpHelper/Steps/Abp/EntityParserStep.cs#L52-L55

When generating crud with entity has inherited interfaces, `Single()` will throw exception.
https://github.com/EasyAbp/AbpHelper.CLI/blob/fe8bb39cf86d5a04615228388eb0f0d50aec1ae4/src/AbpHelper/Steps/Abp/EntityParserStep.cs#L60-L63

**Comment by wakuflair** [comment]
Thanks, it's been fixed.
