### ISSUE TITLE
Can not get type when using composite keys

### ISSUE THREAD

**Issue by RayMMond** [EasyAbp/AbpHelper.CLI#132]
https://github.com/EasyAbp/AbpHelper.CLI/blob/3611da17178389e5d5b16329bccb098708f4f430/src/AbpHelper/Generator/AbpFunctions.cs#L57-L72

`idParameterModel.FullType` does not contain namespace when generating controllers for entity with composite keys, which leads to null reference exception in Line58.

**Comment by wakuflair** [comment]
Thanks.
