### ISSUE TITLE
AbpHelper.CLI 0.7.2 有bug

### ISSUE THREAD

**Issue by amin168** [EasyAbp/AbpHelper.CLI#134]
出现如下错误，0.7.1就没问题

![image](https://user-images.githubusercontent.com/10808093/106565744-3d0af880-656a-11eb-83b0-7ebd2d577736.png)

**Comment by gdlcf88** [comment]
We will check this problem soon, please roll back to v0.7.1 for now:
![C~S9M(BW5UMY)C~1{6MFQTY](https://user-images.githubusercontent.com/30018771/106565953-94a96400-656a-11eb-9a42-d6477aec7704.png)

**Comment by amin168** [comment]
I see

**Comment by wakuflair** [comment]
Can we close now? @gdlcf88

**Comment by gdlcf88** [comment]
Fixed in v0.7.3.
