### ISSUE TITLE
Error while invoking activity activity-81 of workflow 930eb14078264b0fa86b1ce4f717bb9d

### ISSUE THREAD

**Issue by DevRazec** [EasyAbp/AbpHelper.CLI#140]
Hi, I got this error after running the command: abphelper generate crud Patient -d C:\Projects\MSSQL\Devrazec.Application

18:06:00 ERR] Error while invoking activity activity-81 of workflow 930eb14078264b0fa86b1ce4f717bb9d
EasyAbp.AbpHelper.Core.Steps.Common.RunningCommandFailedException: Exception of type 'EasyAbp.AbpHelper.Core.Steps.Common.RunningCommandFailedException' was thrown.
   at EasyAbp.AbpHelper.Core.Steps.Common.RunCommandStep.OnExecuteAsync(WorkflowExecutionContext context, CancellationToken cancellationToken) in D:\a\AbpHelper.CLI\AbpHelper.CLI\src\AbpHelper.Core\Steps\Common\RunCommandStep.cs:line 26
   at Elsa.Services.ActivityInvoker.InvokeAsync(WorkflowExecutionContext workflowContext, IActivity activity, Func`2 invokeAction)
[18:06:00 ERR] Error activity: {
  "Command": {
    "Syntax": "JavaScript",
    "Expression": "`dotnet ef migrations add Added${EntityInfo.Name} -p \"${MigrationProjectFile}\" -s \"${StartupProjectFile}\"`",
    "Type": "System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
  },
  "Name": "AddMigration"
}

**Comment by wakuflair** [comment]
There should be more error info before the first log, can you post them?

**Comment by DevRazec** [comment]
Hi, thanks for helping me. I got some errors in the Domain Layer too.

<img width="1280" alt="Screen Shot 2021-03-15 at 10 30 16" src="https://user-images.githubusercontent.com/49047074/111139916-a0c90e00-8579-11eb-8008-c560678da604.png">
[logs.txt](https://github.com/EasyAbp/AbpHelper.CLI/files/6140664/logs.txt)

**Comment by DevRazec** [comment]
Here I guess some code is missed.

<img width="1280" alt="Screen Shot 2021-03-15 at 11 01 56" src="https://user-images.githubusercontent.com/49047074/111143618-e982c600-857d-11eb-8791-64037faeddf0.png">

**Comment by wakuflair** [comment]
Did you define the properties of your entity in camelCase?
That would cause compilation errors.
Try to use PascalCase, and run abphelper again.
