### ISSUE TITLE
Foreign key entity the curd

### ISSUE THREAD

**Issue by tangningkun** [EasyAbp/AbpHelper.CLI#153]
My entity contains foreign key relationships and cannot be migrated

![image](https://user-images.githubusercontent.com/37114529/130715678-56748bd0-12c5-4daa-b660-818a9e9f054d.png)
![image](https://user-images.githubusercontent.com/37114529/130715693-1633dc56-17f3-467f-aaa0-25b487e1818a.png)

**Comment by gdlcf88** [comment]
Skip the DB migration step, fix the code, and then execute the migration manually.
