### ISSUE TITLE
IMenuContributor ,ConfigureMainMenuAsync

### ISSUE THREAD

**Issue by mrs01dev** [EasyAbp/AbpHelper.CLI#157]
Dear Yuhang Ji
regarding the class
MenuContributor : IMenuContributor 
it has procedure  ConfigureMenuAsync that calls other procedure  ConfigureMainMenuAsync
but there is ConfigureMainMenu instead of ConfigureMainMenuAsync

please rename ConfigureMainMenu to be ConfigureMainMenuAsync
Thanks.

**Comment by gdlcf88** [comment]
#154
