### ISSUE TITLE
Which repository should be injected in CRUD class if an entity has a custom repository?

### ISSUE THREAD

**Issue by gdlcf88** [EasyAbp/AbpHelper.CLI#17]
If a developer use `--custom-repository` to generate codes, maybe we can use:
```
        public TodoAppService(
            ITodoRepository repository) : base(repository)
        {
        }
```
to replace:
```
        public TodoAppService(
            IRepository<Todo, Guid> repository) : base(repository)
        {
        }
```

**Comment by gdlcf88** [comment]
I think we should keep `IRepository<Todo, Guid>`, the reasons:

1. `IRepository<Todo, Guid>` is still usable.
1. The property `Repository` is a `IRepository<Todo, Guid>`, developers cannot use his custom method, unless they create a new `ITodoRepository` property, so we don't need to replace the injection if the generator don't create the property for custom repository.

**Comment by wakuflair** [comment]
So we can close the issue?
