### ISSUE TITLE
Maybe we can add a option to specify UI framework.

### ISSUE THREAD

**Issue by gdlcf88** [EasyAbp/AbpHelper.CLI#19]
Refer to: https://github.com/abpframework/abp/blob/dev/docs/en/CLI.md

Maybe we need a CLI parameter like: `--ui angular` or `-u angular`.

And it could be `--ui none` by default to skip the UI pages generation. (Relate to: https://github.com/EasyAbp/AbpHelper.CLI/issues/15)

There are several reasons:

1. In future, there will be more ABP official UI frameworks and community UI frameworks, even a solution has more than one UI frameworks, so it is hard to do automatic recognition.

1. Developers have experience to use `-u angular` because ABP CLI also has the parameter.

1. GUI will remember the solution information so developers do not need to repeat it. (Not yet implemented)

**Comment by wakuflair** [comment]
ABP makes Razor Pages as the default UI framework, so forcing users to specify a UI option doesn't look so friendly.
For now abphelper detects UI framework automatically, and it seems to work well.
In future, maybe we can add an option to specify the UI framework explicitly, if things get complicated.
