### ISSUE TITLE
Suggestions for command line improvement

### ISSUE THREAD

**Issue by gdlcf88** [EasyAbp/AbpHelper.CLI#2]
This is the current command line demo:
`abphelper C:\MyTodo Todo.cs`

I have some suggestions:

1. **Rename "abphelper" to "abp-helper".**
Of course we should not use CamelCase, but maybe `abp-helper` is a better choice.
2. **Change the input from solution folder to .sln file.**
If we do it, maybe developers can use it directly by select a .sln file without having to learn which folder should be inputted.
3. **Add a required function name to command line.**
In future, AbpHelper may has more functions than the code generation, so we can add a function name likes `generate` after the command `abphelper`.
4. **Entity name don't need .cs suffix.**
If developers input `Todo`, we can assert the filename is "Todo.cs", and if the entity file is not in the default location "C:\MyTodo\src\MyTodo.Domain\Todos\Todo.cs", they can configure the correct path by `--EntityFile C:\MyTodo\src\MyTodo.Domain\Todos\TodoEntity.cs` or `-e C:\MyTodo\src\MyTodo.Domain\Todos\TodoEntity.cs`.
5. **Maybe solution folder input could be omitted.**
Developers can change current folder to C:\MyTodo and run the command line, for this use, solution folder (or .sln file) is not required to input, so we can omit it can provide a way to set the target .sln file likes `-s C:\MyTodo\MyTodo.sln`.

For example:
```
abp-helper generate Todo
abp-helper generate Todo -e C:\MyTodo\src\MyTodo.Domain\Todos\TodoEntity.cs
abp-helper generate Todo -s C:\MyTodo\MyTodo.sln
```

**Comment by wakuflair** [comment]
1. I prefer the `abphelper` form, `abp-helper` needs one more keystroke. Maybe we can wait for more advises.
1. Accpted.
1. Subcommand will be supported.
1. Accpted.
1. Accpted.
