### ISSUE TITLE
Maybe .sln is better than directory for code generation command.

### ISSUE THREAD

**Issue by gdlcf88** [EasyAbp/AbpHelper.CLI#20]
Relate to: https://github.com/EasyAbp/AbpHelper.CLI/issues/19

Today the ABP CLI generate the .sln file in `root` directory for MVC template, but generate it in `/aspnet-core` directory for Angular template.
![3E@$1LLUJ XNG64YS502NN2](https://user-images.githubusercontent.com/30018771/74914572-a3e8dd80-53fd-11ea-8881-35e3c0bc2dd8.png) ![image](https://user-images.githubusercontent.com/30018771/74914664-cd096e00-53fd-11ea-8f40-29bd37efa443.png)

Maybe we should use `-s .sln` instead of `-d root-directory`, reasons:

1. Developers who use Angular may input the `/aspnet-core` directory before he know the mistake (For now the correct input is root directory). The .sln file scheme requires less learning costs.

1. AbpHelper GUI will remember solution configurations, and one day maybe ABP CLI will optimize the directory structure, so there are two different structure that need to be adapted. But if we use .sln file to locating the solution, we will not care about this changing.

1. ABP CLI also use .sln and .csproj, developers have experience. https://github.com/abpframework/abp/blob/dev/docs/en/CLI.md

**Comment by wakuflair** [comment]
For now I still prefer to specify the directoriy.
If ABP team change the project structure of the angular template, .sln would be better.
