### ISSUE TITLE
如何生成带MaxLength、Required的CRUD代码？

### ISSUE THREAD

**Issue by haoyk** [EasyAbp/AbpHelper.CLI#209]
请教个问题，在默认生成的CRUD代码中，DTO和ModelBuilder中都没有长度、必填等信息，我尝试过在Entity中加[Required]
        、[MaxLength(50)]但并不生效。

请问AbpHelper是否支持这个功能？

**Comment by wakuflair** [comment]
验证规则需要自己填加。
