### ISSUE TITLE
feat: suggest using a shorter command

### ISSUE THREAD

**Issue by itryan** [EasyAbp/AbpHelper.CLI#21]
currently `abphelper` is the command to use AbpHelper.Cli, maybe can consider using a shorter name (e.g. `abph`) which will be more convenient.

**Comment by wakuflair** [comment]
Hi,
We believe that the command name should be accurate and not easy to be duplicate. `abphelper` is a more appropriate name under this guidline.

However you can still use the aliasing to make a shorter name for abphelper, for example, in PowerShell you can:

`Set-Alias -Name abph -Value abphelper`

This will set an alias `abph` for `abphelper`. 

Another solution is use [AbpHelper.GUI](https://github.com/EasyAbp/AbpHelper.GUI), it provides many features through GUI.

**Comment by itryan** [comment]
thanks, will close this issue.
