### ISSUE TITLE
Support Custom Domain Root

### ISSUE THREAD

**Issue by holyrong** [EasyAbp/AbpHelper.CLI#210]
version:2.6.0
abp:7.0.3
abp helper gui : CRUD Generator

Domain class inherit chain like blow,**but it can't generate CRUD files** even though the gui returns successful.

Book->MyRoot->AuditedAggregateRoot(or other Root class)

**expose it can support any domain class to generate CRUD files**

**Comment by gdlcf88** [comment]
Try to keep the entity classes simple and refactor the `MyRoot` to `IMyRoot`.

**Comment by holyrong** [comment]
> 

can you give me a sample?

**Comment by holyrong** [comment]
![image](https://user-images.githubusercontent.com/8318475/227690455-65c44f81-da37-4511-a5a9-85ca4931615b.png)

**Comment by holyrong** [comment]
> ![image](https://user-images.githubusercontent.com/8318475/227690455-65c44f81-da37-4511-a5a9-85ca4931615b.png)

it's ok like this.
