### ISSUE TITLE
Support for differing solution name

### ISSUE THREAD

**Issue by nebula2** [EasyAbp/AbpHelper.CLI#218]
The current logic in `EnsureSlnFileExists.EnsureSlnFileExists` expects the solution name in a specific format.

When your setup differs from that, the cli is not really usable due to FileNotFoundException getting thrown.

For example: You have a Domain-Project named `Company.Module.Domain` but your solution is named `company-module.sln`

It would be cool to have an option to one of the following
- skip the check
- option to specify solution file

in the meantime, I altered the code to this

```c#
private void EnsureSlnFileExists(WorkflowExecutionContext context, string projectName)
        {
            string aspNetCoreDir = context.GetVariable<string>(VariableNames.AspNetCoreDir);
            string slnFile = Path.Combine(aspNetCoreDir, $"{projectName}.sln");

            var candidates = Directory.GetFiles(aspNetCoreDir, "*.sln");

            if (!File.Exists(slnFile) && candidates.Length != 1)
            {
                throw new FileNotFoundException(
                    $"The solution file '{projectName}.sln' is not found in '{aspNetCoreDir}'. Make sure you specific the right folder.");
            }
        }
```

And it does not seem to have any negative impact - but I only used controller generation at the moment

**Comment by gdlcf88** [comment]
AbpHelper is made for solutions generated by the startup template. We cannot provide configurations for all customs since it would make AbpHelper hard to use. If you have customized guidelines, fork this project may be a good way.

**Comment by nebula2** [comment]
Thank you, will do :)
