### ISSUE TITLE
support generate entities?

### ISSUE THREAD

**Issue by SmallShrimp** [EasyAbp/AbpHelper.CLI#25]
#### suggest
- Whether to consider support for generating entities?
- Consider reading the PDM file to generate the entities!

**Comment by wakuflair** [comment]
Hi
Generating entities from PDM or database is more like a common generating task. ABPHelper's top priority at present is some help work around ABP development.
Maybe you can generate entites first by other tools, then use AbpHelper.

**Comment by wakuflair** [comment]
Hi @SmallShrimp 
If you have any further suggestion, feel free to reopen this issue.
