### ISSUE TITLE
Mvc UI pages generation EditModal.cshtml code problem.

### ISSUE THREAD

**Issue by gdlcf88** [EasyAbp/AbpHelper.CLI#29]
![image](https://user-images.githubusercontent.com/30018771/76163420-d8d88c80-6180-11ea-925f-a1e866630255.png)

`@inherits MyProject.Web.Pages.MyProjectPage` makes IDE show the error.

**Comment by wakuflair** [comment]
Can it build and run correctly?

**Comment by gdlcf88** [comment]
All correctly.

**Comment by wakuflair** [comment]
So it's just an IDE problem.
