### ISSUE TITLE
Rollback mechanism for the code generator.

### ISSUE THREAD

**Issue by gdlcf88** [EasyAbp/AbpHelper.CLI#3]
We need a way to rollback the code generated by the generator. 

When the program runs in error, even the migration has been executed, we should rollback all the changes, or it will pollute the projects.

**Comment by gdlcf88** [comment]
And maybe the step **update-database** should be executed after all other steps are completed.

**Comment by wakuflair** [comment]
For now it is a bit hard to implement the rollback mechanism, so backup is recommanded.
Use git to commit first, and revert if anything goes wrong. The migrating can also easily rollback using this way.

For **update-database**, putting it in the last step sounds a good idea.
