### ISSUE TITLE
build cli ERROR,copy sbntxt file

### ISSUE THREAD

**Issue by xewn** [EasyAbp/AbpHelper.CLI#31]
error MSB3027: 无法将“F:\github\abptools\AbpHelper.CLI\src\AbpHelper\Templates\Crud\Groups\Test\test\{{ ProjectInfo.FullName }}.EntityFrameworkCore.Tests\EntityFrameworkCore\{{ EntityInfo.NamespaceLastPart }}\{{ EntityInfo.Name }}RepositoryTests.cs.sbntxt”复制到“bin\Debug\netcoreapp3.1\publish\Templates\Crud\Groups\Test\test\{{ ProjectInfo.FullName }}.EntityFrameworkCore.Tests\EntityFrameworkCore\{{ EntityInfo.NamespaceLastPart }}\{{ EntityInfo.Name }}RepositoryTests.cs.sbntxt”。超出了重试计数 10。失败。

**Comment by xewn** [comment]
编译 cli工程时，报错。一直重试复制模板文件，然后就失败了。
我猜，是不是文件路径太长造成的？我用vs 2019编译的

**Comment by wakuflair** [comment]
Yeah maybe you can make the path shorter and retry
