### ISSUE TITLE
CRUD permissions generation.

### ISSUE THREAD

**Issue by gdlcf88** [EasyAbp/AbpHelper.CLI#33]
In `CrudAppService` we have `GetPolicyName`, `GetListPolicyName`, `CreatePolicyName`, `UpdatePolicyName` and `DeletePolicyName`, maybe the basic CRUD permissions should be generated.

**Comment by gdlcf88** [comment]
Please also remember to generate permission overrides in the CRUD service.

**Comment by gdlcf88** [comment]
MyModuleMenuContributor should check the default permission too.

**Comment by gdlcf88** [comment]
MyModuleMenuContributor should check the default permission too.

**Comment by gdlcf88** [comment]
And it should check permissions for edit/delete action in index.js and create action in Index.cshtml.

**Comment by wakuflair** [comment]
Done.
