### ISSUE TITLE
Need create/update info models generation.

### ISSUE THREAD

**Issue by gdlcf88** [EasyAbp/AbpHelper.CLI#37]
![image](https://user-images.githubusercontent.com/30018771/76604766-494d2800-654a-11ea-918b-94021935d9a8.png)

It is not a good way to add Bootstrap attributes to creation DTO.

Developers may need a CreateUpdateTodoInfoModel (or two separated info models), so they can custom their form.

**Comment by wakuflair** [comment]
Duplicated: https://github.com/EasyAbp/AbpHelper.CLI/issues/39
