### ISSUE TITLE
The code generator should check duplication.

### ISSUE THREAD

**Issue by gdlcf88** [EasyAbp/AbpHelper.CLI#4]
![image](https://user-images.githubusercontent.com/30018771/74186034-d586d980-4c84-11ea-9e76-dae92fac3ed9.png)

When we try to generate codes for `Todo` twice, the generator don't know that the code is already existing. So it should check duplication first.

**Comment by wakuflair** [comment]
I thought no one would generate the same entity twice, but one might modify the fields and generate again.
So this will be fixed.
