### ISSUE TITLE
Module code generator: Move all the EntityName folders into ModuleName folder in Pages of Web project.

### ISSUE THREAD

**Issue by gdlcf88** [EasyAbp/AbpHelper.CLI#40]
From:
![image](https://user-images.githubusercontent.com/30018771/77052147-57e28600-6a07-11ea-91ab-4144e7291dfe.png)
To:
![image](https://user-images.githubusercontent.com/30018771/77052176-65980b80-6a07-11ea-8493-1eba30607cf4.png)

Reasons:
1. ModuleName folder exist when the solution was generated.
1. Avoid duplicate names with other modules and applications.
1. The blogging module does the same.

**Comment by gdlcf88** [comment]
https://github.com/EasyAbp/AbpHelper.CLI/commit/75fe3d1ee01f9d259de942e9aeda5944d6acdb78

**Comment by gdlcf88** [comment]
![image](https://user-images.githubusercontent.com/30018771/77497569-9bfedc00-6e88-11ea-8cea-99a478ce6772.png)
Hi @wakuflair, I try the new version 0.2.0, it looks unchanged.

**Comment by wakuflair** [comment]
You need put your `CacheItem` entity in `EasyAbp.CacheManagement.CacheManagement.CacheItems` namespace in order to generate the correct web files.

It seems a little mess, maybe resolving https://github.com/abpframework/abp/issues/3314 will make things better.

Closed for now.
