### ISSUE TITLE
Module code generator: folder structure adjustment.

### ISSUE THREAD

**Issue by gdlcf88** [EasyAbp/AbpHelper.CLI#42]
According to [Blogging module](https://github.com/abpframework/abp/tree/dev/modules/blogging), module's entities should have full directory layers like `EasyAbp/MyModule/Todos/Todo.cs`.

So I tried:
![image](https://user-images.githubusercontent.com/30018771/77191368-d3caf400-6b15-11ea-9a9a-c39b69714fde.png)

But got:
![image](https://user-images.githubusercontent.com/30018771/77191796-797e6300-6b16-11ea-85fa-0d232ba1c286.png)

**Comment by gdlcf88** [comment]
Relate to: https://github.com/EasyAbp/AbpHelper.CLI/issues/40

**Comment by wakuflair** [comment]
Resolved with #40
