### ISSUE TITLE
Problems with repeated generation of constructors.

### ISSUE THREAD

**Issue by gdlcf88** [EasyAbp/AbpHelper.CLI#43]
![image](https://user-images.githubusercontent.com/30018771/77495907-bafb6f00-6e84-11ea-8a5f-0079c0325d9e.png)

**Comment by wakuflair** [comment]
This is because you changed the template.

**Comment by gdlcf88** [comment]
I did not change the template.

If my entity class already has .ctor methods, it will ignore them and generate a new public .ctor method like the screenshot you see.

**Comment by wakuflair** [comment]
The commit https://github.com/EasyAbp/AbpHelper.CLI/commit/1809b4ff0170825af4b9736f00ab9e3e3f8ce3a6 deletes the space char before 'base', cause following generated text different.

**Comment by gdlcf88** [comment]
I am using released cli version (0.2.0), it happens before this commit.

The problem is that format differences should be allowed, people could create .ctor manually, it just need to judge whether the .ctor methods exist or not, and don't care about the differences in formats

**Comment by wakuflair** [comment]
OK,  will see what can I do with the format.
