### ISSUE TITLE
Need a module parent menu item.

### ISSUE THREAD

**Issue by gdlcf88** [EasyAbp/AbpHelper.CLI#45]
Need parent menu item to group the Entity menu items.

For example:

Menu:TodoManagement
---- Menu:TodoManagement.Todos
-------- Menu:TodoManagement.Todos.Todo

Refer to https://github.com/abpframework/abp/blob/dev/modules/blogging/src/Volo.Blogging.Web/BloggingMenuContributor.cs#L27

**Comment by gdlcf88** [comment]
By default, developers don't want every entity of a module to have a first-level menu item.

**Comment by wakuflair** [comment]
It's a bit tricky to handle the menu generation, so refer to https://github.com/EasyAbp/AbpHelper.CLI/issues/41, developers should adjust menu structure manually.
