### ISSUE TITLE
给工程文件添加common.props引用

### ISSUE THREAD

**Issue by xewn** [EasyAbp/AbpHelper.CLI#46]
给每个工程文件*.csproj添加common.props

**Comment by xewn** [comment]
或者也可以合并成一个功能，自动在解决方案目录下生成common.props、configureawait.props文件，在工程目录下生成FodyWeavers.xml文件。同时修改工程文件，引用两个props文件。

**Comment by wakuflair** [comment]
Not very clear about your issue, closed.

**Comment by xewn** [comment]
问题不清楚，你可以问？你就直接关闭掉哇？

**Comment by wakuflair** [comment]
You need to describe your issues in more detail: 
* What problem did you encounter?
* What's your purpose?
* What do you want to achieve?

And last not least, please use English, in order to let others understand you more easily.

**Comment by xewn** [comment]
`
<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\..\configureawait.props" />
  <Import Project="..\..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>Volo.Abp</AssemblyName>
    <PackageId>Volo.Abp</PackageId>
    <AssetTargetFallback>$(AssetTargetFallback);portable-net45+win8+wp8+wpa81;</AssetTargetFallback>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <RootNamespace />
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Volo.Abp.Core\Volo.Abp.Core.csproj" />
  </ItemGroup>
</Project>
`
Add a reference to common.props inside this file（*.csproj）

**Comment by wakuflair** [comment]
What's the purpose of doing this?

**Comment by xewn** [comment]
你要不就用中文吧，别扭不？
你不得把dll的公共配置放在common.props里面？
你有30个模块，你如何管理他们公共的配置信息呢？
configureawait.props  这个里面不是统一来配置ConfigureAwait.Fody的？
[EasyAbpGuide](https://github.com/EasyAbp/EasyAbpGuide/blob/master/Module-Development-Specification.md#using-configureawaitfody)

**Comment by wakuflair** [comment]
AbpHelper.CLI is not an abp module, it's just one dotnet tool with only one assembly, so no need to use common.props.
And for the same reason, it's not a library supposed to be called by other apps/libraries, so no need to use ConfigureAwait.Fody.

**Comment by xewn** [comment]
你完全理解错了。我的意思是，用cli给其他的模块添加这些引用。不是给cli自己添加。

**Comment by xewn** [comment]
比如我，通过cli创建了一个新模块，这个模块本来是没有引用common.props的，也没配置ConfigureAwait.Fody的。哪如何使用 cli给模块添加这些呢？
