### ISSUE TITLE
给每个工程目录添加FodyWeavers.xml文件

### ISSUE THREAD

**Issue by xewn** [EasyAbp/AbpHelper.CLI#48]
每个工程的*.csproj文件同目录，添加FodyWeavers.xml文件

**Comment by wakuflair** [comment]
Not very clear about your issue, closed.

**Comment by xewn** [comment]
![fodyweavers.xml](https://user-images.githubusercontent.com/1423410/77840889-983bc400-71be-11ea-9896-e70a978e8eeb.jpg)
