### ISSUE TITLE
Menu items name improvement.

### ISSUE THREAD

**Issue by gdlcf88** [EasyAbp/AbpHelper.CLI#49]
Refer to Volo's BloggingModule, `Menu:Blog` should be `Menu:Blogs`.
https://github.com/EasyAbp/AbpHelper.CLI/blob/1809b4ff0170825af4b9736f00ab9e3e3f8ce3a6/src/AbpHelper/Templates/Crud/Localization.sbntxt#L2

**Comment by wakuflair** [comment]
I prefer to leave it as single form.
The single / plural forms are not always uniform in ABP modules.

**Comment by wakuflair** [comment]
OK, use entity's `NamespaceLastPart` as the menu name
