### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by zhk0603** [EasyAbp/AbpHelper.CLI#51]
我尝试编译出现如下错误，请问这是怎么回事？

![image](https://user-images.githubusercontent.com/15643960/78529844-1af2fd80-7815-11ea-8e92-592d0f70572d.png)

![image](https://user-images.githubusercontent.com/15643960/78529858-247c6580-7815-11ea-9983-13a221884257.png)

**Comment by zhk0603** [comment]
第一个问题，好像是路径太长了，我缩短了路径，可以了。
但是第二个： ”指定的 DateTimeOffset 不能转换为 Zip 文件时间戳“，这是什么问题

**Comment by wakuflair** [comment]
See https://github.com/NuGet/Home/issues/7001
