### ISSUE TITLE
Improving DeletionConfirmationMessage generation

### ISSUE THREAD

**Issue by gdlcf88** [EasyAbp/AbpHelper.CLI#56]
For now it is:
`"ResourceItemDeletionConfirmationMessage": "Are you sure to delete the resourceitem {0}?",`

The better one is:
`"ResourceItemDeletionConfirmationMessage": "Are you sure to delete the resource item {0}?",`

**Comment by wakuflair** [comment]
Use camel case instead of lower case.
But developers shoud change this message to a more appropriate one.
