### ISSUE TITLE
Get LocalizationResourceName from PaymentsResource class

### ISSUE THREAD

**Issue by gdlcf88** [EasyAbp/AbpHelper.CLI#59]
```
using Volo.Abp.Localization;

namespace EasyAbp.EShop.Payments.Localization
{
    [LocalizationResourceName("EasyAbpEShopPayments")]
    public class PaymentsResource
    {
        
    }
}
```

If a developer change the `LocalizationResourceName`, the generated index.js file is better to use the right resource name:

`var l = abp.localization.getResource('EasyAbpEShopPayments');`

**Comment by wakuflair** [comment]
This needs additional parsing process.

AbpHelper respects the ABP startup template content. If developers modify the ABP template content, they should also modify the AbpHelper template.
