### ISSUE TITLE
Maybe the namespace of dtos should follow the entity.

### ISSUE THREAD

**Issue by gdlcf88** [EasyAbp/AbpHelper.CLI#6]
![image](https://user-images.githubusercontent.com/30018771/74187417-74acd080-4c87-11ea-8a5d-9d966a417368.png)

I generate codes for entity `Todo2` which in the folder `Todos` instead of `Todo2s`, and the dtos are created in `Todo2s` folder. Maybe Todo2 in Todos folder/namespace should be allowed. What do you think? @wakuflair

**Comment by wakuflair** [comment]
Make sense
