### ISSUE TITLE
Menu item Name/DisplayName optimization

### ISSUE THREAD

**Issue by gdlcf88** [EasyAbp/AbpHelper.CLI#62]
When I create both the entities `Todo` and `Todo2` in the same folder **Todos**, the name and the display name of the menu item are not correct:
![image](https://user-images.githubusercontent.com/30018771/82465062-6a556a80-9af1-11ea-8b22-fe47b5010485.png)
![image](https://user-images.githubusercontent.com/30018771/82465070-6d505b00-9af1-11ea-9ff2-8b2b9939e730.png)

**Comment by wakuflair** [comment]
Two options:
1. Use entity name
1. Use plural form of the entity name

Which is better? @gdlcf88

**Comment by gdlcf88** [comment]
I think the second option is better and the first option is OK, too.

**Comment by wakuflair** [comment]
I will take the first option:)

Since Option 2 depends on the [Humanizer](https://github.com/Humanizr/Humanizer) library.
