### ISSUE TITLE
AbpHelper.CLI ,entity constructors , issue ,extra comma

### ISSUE THREAD

**Issue by mrs01dev** [EasyAbp/AbpHelper.CLI#70]
Dear all
AbpHelper.CLI adds extra comma "," to the class constructors  , as the fallowing

 public myClass(Guid id, ) : base(id)
        {
        }
Thanks , best regards

**Comment by wakuflair** [comment]
Hi @mrs01dev 
Could you provide your entity definition code?

**Comment by mrs01dev** [comment]
I am sorry for the delay.
Please note the last constructor.
The End constructor was added by AbpHelper.CLI

 public class ItemData : FullAuditedAggregateRoot<Guid>
    {
        public string ItemTag;
        public ulong ItemSerialNumber;
        public string ItemName;



        protected ItemData()
        {
        }


        public ItemData(

                   [NotNull] ulong _ItemSerialNumber,
                   string _ItemTag = null,
                   string _ItemName = null

                   )
        {
           


            ItemSerialNumber = _ItemSerialNumber;
            ItemTag = _ItemTag;
            ItemName = _ItemName;

        }

        public ItemData(Guid id) : base(id)
        {
        }

        public ItemData(Guid id, ) : base(id)
        {
        }
    }

**Comment by wakuflair** [comment]
Hi 
It's fixed by the latest vesrion of the abphelper(0.4.1), would you try again？

**Comment by wakuflair** [comment]
Closed because long time no response.
