### ISSUE TITLE
Update the menu code generation rule.

### ISSUE THREAD

**Issue by gdlcf88** [EasyAbp/AbpHelper.CLI#77]
According to https://github.com/abpframework/abp/commit/76f9e65ad08566ce2bee61238297c7ad065e3c8f, we should update the generation rule.

**Comment by gdlcf88** [comment]
Should also update the value of `PageLayout.Content.MenuItemName`  in **Index.cshtml**.

**Comment by gdlcf88** [comment]
Update all the EasyAbp modules when this change is complete.

**Comment by wakuflair** [comment]
Wait for https://github.com/abpframework/abp/pull/5057
