### ISSUE TITLE
GUI needs a sub command to get the UI framework name of the selected solution.

### ISSUE THREAD

**Issue by gdlcf88** [EasyAbp/AbpHelper.CLI#8]
![image](https://user-images.githubusercontent.com/30018771/74232230-54baf280-4d03-11ea-8454-82ba9a49737b.png)

GUI does not know which UI framework the selected solution uses, maybe we should create a new sub command to get UI framework name so GUI can show available options for developers.

**Comment by gdlcf88** [comment]
If https://github.com/EasyAbp/AbpHelper.CLI/issues/19 is accepted, I will close this issue.

**Comment by wakuflair** [comment]
How about adding a sub command `abphelper project-info` to return the project info?
But the GUI must capture the console output and parse it.

**Comment by gdlcf88** [comment]
There is no need for cli to provide this feature because GUI should remember the UI framework of solutions when developers add them to the solution management. https://github.com/EasyAbp/AbpHelper.GUI/issues/6
