### ISSUE TITLE
Optimize the CLI installation command in README.md

### ISSUE THREAD

**Issue by gdlcf88** [EasyAbp/AbpHelper.CLI#9]
https://docs.abp.io/en/abp/latest/CLI#installation
Abp CLI doc show the following command:
`dotnet tool install -g Volo.Abp.Cli`

Maybe we should use:
`dotnet tool install -g EasyAbp.AbpHelper.Cli` or `dotnet tool install -g EasyAbp.AbpHelper`
to replace:
`dotnet tool install AbpHelper -g`

What do you think? @wakuflair

**Comment by wakuflair** [comment]
I will check if the package id can be changed.

**Comment by wakuflair** [comment]
The package id changed to `EasyAbp.AbpHelper`.
Since it's not a preview version, so the installation command is simplified too.
