### ISSUE TITLE
EF Migration helper

### ISSUE THREAD

**Issue by gdlcf88** [EasyAbp/AbpHelper.CLI#90]
Help developers to add migrations and update the databases, it automatically finds the correct startup project and is especially helpful for JetBrains Rider users.

It uses `dotnet ef` command, so putting it in the "AbpHelperCLI - EF Core tools" category may be a good idea.

**Comment by wakuflair** [comment]
Done with https://github.com/EasyAbp/AbpHelper.CLI/commit/1dcfbf61fda62441b8c6a834a4edf40b59e99f21
