### ISSUE TITLE
Modules install/update helper

### ISSUE THREAD

**Issue by gdlcf88** [EasyAbp/AbpHelper.CLI#94]
The command may be: `abphelper module update EasyAbp.EShop 1.0.0`

It searches all the PackageReference starts with `EasyAbp.EShop` and upgrades them to version 1.0.0.

**Comment by wakuflair** [comment]
Should also support install 3rd-party abp modules. The command may be: `abphelper module add EasyAbp.EShop`.
* If no version specified, install the latest version
* Provide a composite option allow developers to install individual packages, for example:  `-d` means "Domain" package, `-dacw` menas "Domain, Application, Contract and Web" packages
